import {
  faCircleCheck as farCircleCheck,
  faEye as farEye,
  faEyeSlash as farEyeSlash,
} from "@fortawesome/free-regular-svg-icons";
import {
  faAddressBook,
  faAward,
  faBuilding,
  faCircleCheck as fasCircleCheck,
  faCircleXmark,
  faChartLine,
  faDownload,
  faGlobe,
  faHeadset,
  faPeopleLine,
  faPlay,
  faScaleBalanced,
  faShield,
  faShieldAlt,
  faTriangleExclamation,
  faUser,
  faEye,
  faEyeSlash,
} from "@fortawesome/free-solid-svg-icons";

export const byPrefixAndName = {
  far: {
    "circle-check": farCircleCheck,
    eye: farEye,
    "eye-slash": farEyeSlash,
  },
  fas: {
    "address-book": faAddressBook,
    award: faAward,
    building: faBuilding,
    "circle-check": fasCircleCheck,
    "circle-xmark": faCircleXmark,
    "chart-line": faChartLine,
    download: faDownload,
    globe: faGlobe,
    headset: faHeadset,
    "people-line": faPeopleLine,
    play: faPlay,
    "scale-balanced": faScaleBalanced,
    shield: faShield,
    "shield-alt": faShieldAlt,
    "eye": faEye,
    "triangle-exclamation": faTriangleExclamation,
    user: faUser,
  },
};
